### PR TITLE
Add build dependency of pytest

### PR DESCRIPTION
**Pull request by apandada1**
It was failing to build on Launchpad, and showed `ModuleNotFoundError: No module named 'pytest'`. After adding this build dependency the PPA package works again.

### CODE REVIEW

**Comment by alexhuntley** [comment]
That's weird, is Launchpad trying to run the tests?

**Comment by apandada1** [comment]
Launchpad (and any proper Debian packaging system) runs some kind of tests before packaging python apps. I have noticed (in other software) that it even points out syntax error when a slightly old code may not work with a new release of python.

[Here](https://launchpadlibrarian.net/519333584/buildlog_ubuntu-focal-amd64.plots_0.4.3-0~202101240024~ubuntu20.04.1_BUILDING.txt.gz) is one of those build logs (the error `ModuleNotFoundError: No module named 'pytest'` is at the very end).

**Comment by alexhuntley** [comment]
> Launchpad (and any proper Debian packaging system) runs some kind of tests before packaging python apps. I have noticed (in other software) that it even points out syntax error when a slightly old code may not work with a new release of python.

Interesting, I wasn't aware of this.

> More interestingly, the `pytest` did not go into the dependency of the final debian package.

It might be because pytest isn't listed as a requirement in setup.py?

**Comment by apandada1** [comment]
> It might be because pytest isn't listed as a requirement in setup.py?

It may be so, but I don't know if `pytest` is really required for the
program to run. In my computer pytest is not installed, and still the
program runs fine.

**Comment by alexhuntley** [comment]
Yes pytest is only needed to run the tests, the app itself doesn't require it.

**Pull request merged**
