### PR TITLE
Created PPA and updated README with installation instructions

### PR DESCRIPTION
**Pull request by apandada1**
I have created a [PPA](https://launchpad.net/~apandada1/+archive/ubuntu/plots) for Ubuntu and derivatives. I have tested that it works in Linux Mint 20.
The .deb package automatically downloads the `Latin Modern Math` font after the installation, and the user experience should be identical to the flatpak version (but the total download size would be less than 1 MB).

I have also added the installation instructions for the PPA and with `setup.py`.

Once this is merged, I can also create a `Daily Builds` PPA, which will use the latest code in this repository to automatically build a .deb package in Launchpad.

### CODE REVIEW

**Comment by alexhuntley** [comment]
Thanks for this. I have just a few comments:
- Shouldn't the binary package also depend on `python3-gi`, `python3-opengl`, `python3-numpy` and `python3-jinja2`? At the moment they are only Build-Depends.
- To install the manual, we need to install the contents of ```help/C/``` into `/usr/share/help/C/plots/`. If any translations of the manual are added, they will also need to be installed from `help/LANG/` into `/usr/share/help/LANG/plots/` where `LANG` could be any locale.
- The debian and ubuntu repositories already contain a package called `fonts-lmodern` which provides ```/usr/share/texmf/fonts/opentype/public/lm-math/latinmodern-math.otf``` (among other fonts). We should depend on this instead of downloading the font at install time.

**Comment by apandada1** [comment]
- The python dependencies are automatically calculated during building (the field {python3-depends} takes care of that). After building the debian package does depend on those packages.
```
$ apt show plots
Package: plots
Version: 0.1.5-0~202101110426~ubuntu20.04.1
Priority: optional
Section: python
Maintainer: Archisman Panigrahi <apandada1@gmail.com>
Installed-Size: 142 kB
Depends: python3-gi, python3-jinja2, python3-numpy, python3-opengl, python3:any, gir1.2-gtk-3.0
Download-Size: 22.6 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/apandada1/plots/ubuntu focal/main amd64 Packages
Description: Simple graph plotting
 Plots makes it easy to visualise mathematical formulae. In addition to basic arithmetic operations, it supports trigonometric, hyperbolic, exponential and logarithmic functions, as well as arbitrary sums and products.
 .
 Plots is designed to integrate well with the GNOME desktop and takes advantage of modern hardware using OpenGL.
```
- I created these yesterday before the manual was not added. I will push a commit to take care of the manual.
- I did not know about the `fonts-lmodern` package. I will add that, and remove the `postinst` script.

**Comment by apandada1** [comment]
For now I am adding the line in `debian/install` to copy the contents of `help/C/` into `/usr/share/help/C/plots/`. We have to add a new line to `debian/install` when translations for a new locale are available.

I don't know if this can be dynamically implemented (so that the packaging system will automatically detect all the translations and copy them appropriately).

**Comment by alexhuntley** [comment]
OK that sounds reasonable. It might be possible to use `setup.py` for this in the future.

**Comment by apandada1** [comment]
I have pushed a commit containing the changes we discussed. **Don't** merge right now. I have configured Launchpad to automatically build the PPA package from my fork. Once it is built, I will test it, and then let you know.

**Comment by apandada1** [comment]
It works.
Screenshot from 2021-01-12 10-56-59

Screenshot from 2021-01-12 10-58-33

**Comment by alexhuntley** [comment]
Fantastic! Thanks for contributing :)

**Comment by apandada1** [comment]
Henceforth, can you update the `debian/changelog` when you make a new major release? (In case you are using debian a based system, use the command `dch` in the directory of the repo. Otherwise, just copy paste the current entry into a new one, and change the version number, approximate time, and my name/email to your name/email).

Then I won't have to send a pull request just to update the version number in the changelog. I am watching releases, and will build it in Launchpad when you release a new version.

**Comment by alexhuntley** [comment]
That shouldn't be a problem. (and I'm using Ubuntu fortunately!)

**Comment by apandada1** [comment]
Someone suggested a way to take care of the translations. We can implement this once translations become available. https://askubuntu.com/a/1307069/124466

**Pull request merged**
