### PR TITLE
Create basic-functions.page

### PR DESCRIPTION
**Pull request by airon90**
Added Italian page

### CODE REVIEW

**Comment by alexhuntley** [comment]
Thanks, this looks fine but doesn't actually do anything yet (the English manual is still shown).

I think you need (at least) `index.page` and `legal.xml`.

**Comment by airon90** [comment]
I will translate everything during next week, so please start accept my contribution ;)

**Comment by alexhuntley** [comment]
OK it's merged. 

But normally I think you'd want to do the whole thing as a single pull request ;)

**Comment by airon90** [comment]
> But normally I think you'd want to do the whole thing as a single pull request ;)

I don't have time rn and I don't know how to do that. I'm not good in using git commands so I use Github website to make edits

**Comment by alexhuntley** [comment]
I've just added the help pages to [Weblate](https://hosted.weblate.org/projects/plots/), hopefully it makes things easier :)

**Pull request merged**
