### PR TITLE
CI: update main branch name

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
old habits I guess

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
This should fix the grey CI badge issue :)

**Comment by alexhuntley** [comment]
Wonderful, thank you :)

**Comment by bilelmoussaoui** [comment]
Happy to help :)

**Comment by bilelmoussaoui** [comment]
Also, I think you might find this interesting circle.gnome.org/

**Comment by alexhuntley** [comment]
Thanks, I'll look into it!

**Pull request merged**
