### PR TITLE
[README] Mention AUR packages.

### PR DESCRIPTION
**Pull request by ahmubashshir**

### CODE REVIEW

**Comment by Biswa96** [comment]
OMG! I have added a AUR with python-plots name.

**Comment by ahmubashshir** [comment]
As it's not a python module, it shouldn't have `python-` prepended[^1].

[^1]: https://wiki.archlinux.org/index.php/Python_package_guidelines#Package_naming

**Comment by Biswa96** [comment]
OK, I will ask TUs to remove my one. Also thank you for adding the package 🤟

**Comment by ahmubashshir** [comment]
Thanks :3

**Comment by alexhuntley** [comment]
Thank you both for your contributions!

@ahmubashshir I don't run Arch so I can't test your package, but it looks reasonable to me. Please could you make sure the help browser, equation font (the correct one as seen in the screenshots), and icons are all working? And also that the app shows up properly in the applications menu and is launchable from the desktop entry?

Thanks again :)

**Comment by ahmubashshir** [comment]
> Thank you both for your contributions!
> 
> @ahmubashshir I don't run Arch so I can't test your package, but it looks reasonable to me. Please could you make sure the help browser, equation font (the correct one as seen in the screenshots), and icons are all working? And also that the app shows up properly in the applications menu and is launchable from the desktop entry?
> 
> Thanks again :)

Yes, everything is working as expected.

**Comment by alexhuntley** [comment]
Great, it's been merged. I'll let you know if the packaging needs any modifications in the future.

**Pull request merged**
